/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as FeiraRouteImport } from './routes/feira'
import { Route as DestinosRouteImport } from './routes/destinos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AplicarRouteImport } from './routes/aplicar'
import { Route as InscricaoSlugRouteImport } from './routes/inscricao.$slug'
import { Route as EdicoesSlugRouteImport } from './routes/edicoes.$slug'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const FeiraRoute = FeiraRouteImport.update({
  id: '/feira',
  path: '/feira',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosRoute = DestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicarRoute = AplicarRouteImport.update({
  id: '/aplicar',
  path: '/aplicar',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoSlugRoute = InscricaoSlugRouteImport.update({
  id: '/inscricao/$slug',
  path: '/inscricao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesSlugRoute = EdicoesSlugRouteImport.update({
  id: '/edicoes/$slug',
  path: '/edicoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplicar': typeof AplicarRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/edicoes/$slug': typeof EdicoesSlugRoute
  '/feira': typeof FeiraRoute
  '/guia': typeof GuiaRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/sobre': typeof SobreRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplicar': typeof AplicarRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/edicoes/$slug': typeof EdicoesSlugRoute
  '/feira': typeof FeiraRoute
  '/guia': typeof GuiaRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/sobre': typeof SobreRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplicar': typeof AplicarRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/edicoes/$slug': typeof EdicoesSlugRoute
  '/feira': typeof FeiraRoute
  '/guia': typeof GuiaRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/sobre': typeof SobreRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aplicar'
    | '/contato'
    | '/destinos'
    | '/edicoes/$slug'
    | '/feira'
    | '/guia'
    | '/inscricao/$slug'
    | '/sobre'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplicar'
    | '/contato'
    | '/destinos'
    | '/edicoes/$slug'
    | '/feira'
    | '/guia'
    | '/inscricao/$slug'
    | '/sobre'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/aplicar'
    | '/contato'
    | '/destinos'
    | '/edicoes/$slug'
    | '/feira'
    | '/guia'
    | '/inscricao/$slug'
    | '/sobre'
    | '/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplicarRoute: typeof AplicarRoute
  ContatoRoute: typeof ContatoRoute
  DestinosRoute: typeof DestinosRoute
  EdicoesSlugRoute: typeof EdicoesSlugRoute
  FeiraRoute: typeof FeiraRoute
  GuiaRoute: typeof GuiaRoute
  InscricaoSlugRoute: typeof InscricaoSlugRoute
  SobreRoute: typeof SobreRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$slug': {
      id: '/inscricao/$slug'
      path: '/inscricao/$slug'
      fullPath: '/inscricao/$slug'
      preLoaderRoute: typeof InscricaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feira': {
      id: '/feira'
      path: '/feira'
      fullPath: '/feira'
      preLoaderRoute: typeof FeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos': {
      id: '/destinos'
      path: '/destinos'
      fullPath: '/destinos'
      preLoaderRoute: typeof DestinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicar': {
      id: '/aplicar'
      path: '/aplicar'
      fullPath: '/aplicar'
      preLoaderRoute: typeof AplicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/$slug': {
      id: '/edicoes/$slug'
      path: '/edicoes/$slug'
      fullPath: '/edicoes/$slug'
      preLoaderRoute: typeof EdicoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplicarRoute: AplicarRoute,
  ContatoRoute: ContatoRoute,
  DestinosRoute: DestinosRoute,
  EdicoesSlugRoute: EdicoesSlugRoute,
  FeiraRoute: FeiraRoute,
  GuiaRoute: GuiaRoute,
  InscricaoSlugRoute: InscricaoSlugRoute,
  SobreRoute: SobreRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
